# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Job_UI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JobSchedulerUI(object):
    def setupUi(self, JobSchedulerUI):
        JobSchedulerUI.setObjectName("JobSchedulerUI")
        JobSchedulerUI.resize(929, 851)
        self.centralwidget = QtWidgets.QWidget(JobSchedulerUI)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.JobInfoPanel = QtWidgets.QTableWidget(self.centralwidget)
        self.JobInfoPanel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.JobInfoPanel.setObjectName("JobInfoPanel")
        self.JobInfoPanel.setColumnCount(0)
        self.JobInfoPanel.setRowCount(0)
        self.verticalLayout_5.addWidget(self.JobInfoPanel)
        spacerItem = QtWidgets.QSpacerItem(50, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.JobInProgressCounter = QtWidgets.QLabel(self.centralwidget)
        self.JobInProgressCounter.setObjectName("JobInProgressCounter")
        self.verticalLayout_14.addWidget(self.JobInProgressCounter)
        self.JobInPlanCheckCounter = QtWidgets.QLabel(self.centralwidget)
        self.JobInPlanCheckCounter.setObjectName("JobInPlanCheckCounter")
        self.verticalLayout_14.addWidget(self.JobInPlanCheckCounter)
        self.JobListColumn = QtWidgets.QColumnView(self.centralwidget)
        self.JobListColumn.setObjectName("JobListColumn")
        self.verticalLayout_14.addWidget(self.JobListColumn)
        self.horizontalLayout_9.addLayout(self.verticalLayout_14)
        spacerItem1 = QtWidgets.QSpacerItem(10, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.CreateJobWidget = QtWidgets.QWidget()
        self.CreateJobWidget.setObjectName("CreateJobWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.CreateJobWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.CreateJobWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.designerName_txt = QtWidgets.QLineEdit(self.CreateJobWidget)
        self.designerName_txt.setObjectName("designerName_txt")
        self.horizontalLayout.addWidget(self.designerName_txt)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.jobName = QtWidgets.QLabel(self.CreateJobWidget)
        self.jobName.setObjectName("jobName")
        self.horizontalLayout_2.addWidget(self.jobName)
        self.JobName_txt = QtWidgets.QLineEdit(self.CreateJobWidget)
        self.JobName_txt.setObjectName("JobName_txt")
        self.horizontalLayout_2.addWidget(self.JobName_txt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.contractorName = QtWidgets.QLabel(self.CreateJobWidget)
        self.contractorName.setObjectName("contractorName")
        self.horizontalLayout_5.addWidget(self.contractorName)
        self.Contractor_txt = QtWidgets.QLineEdit(self.CreateJobWidget)
        self.Contractor_txt.setObjectName("Contractor_txt")
        self.horizontalLayout_5.addWidget(self.Contractor_txt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.eng_days = QtWidgets.QLabel(self.CreateJobWidget)
        self.eng_days.setObjectName("eng_days")
        self.horizontalLayout_3.addWidget(self.eng_days)
        self.EngDays_spin = QtWidgets.QSpinBox(self.CreateJobWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EngDays_spin.sizePolicy().hasHeightForWidth())
        self.EngDays_spin.setSizePolicy(sizePolicy)
        self.EngDays_spin.setObjectName("EngDays_spin")
        self.horizontalLayout_3.addWidget(self.EngDays_spin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.draft_days = QtWidgets.QLabel(self.CreateJobWidget)
        self.draft_days.setObjectName("draft_days")
        self.horizontalLayout_4.addWidget(self.draft_days)
        self.DftDays_spin = QtWidgets.QSpinBox(self.CreateJobWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DftDays_spin.sizePolicy().hasHeightForWidth())
        self.DftDays_spin.setSizePolicy(sizePolicy)
        self.DftDays_spin.setObjectName("DftDays_spin")
        self.horizontalLayout_4.addWidget(self.DftDays_spin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.start_date = QtWidgets.QLabel(self.CreateJobWidget)
        self.start_date.setObjectName("start_date")
        self.horizontalLayout_19.addWidget(self.start_date)
        self.EstStartDay_date = QtWidgets.QDateEdit(self.CreateJobWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EstStartDay_date.sizePolicy().hasHeightForWidth())
        self.EstStartDay_date.setSizePolicy(sizePolicy)
        self.EstStartDay_date.setCalendarPopup(True)
        self.EstStartDay_date.setObjectName("EstStartDay_date")
        self.horizontalLayout_19.addWidget(self.EstStartDay_date)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_19 = QtWidgets.QLabel(self.CreateJobWidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_27.addWidget(self.label_19)
        self.APN_txt = QtWidgets.QLineEdit(self.CreateJobWidget)
        self.APN_txt.setObjectName("APN_txt")
        self.horizontalLayout_27.addWidget(self.APN_txt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_20 = QtWidgets.QLabel(self.CreateJobWidget)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_28.addWidget(self.label_20)
        self.Address_txt = QtWidgets.QLineEdit(self.CreateJobWidget)
        self.Address_txt.setObjectName("Address_txt")
        self.horizontalLayout_28.addWidget(self.Address_txt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.CreateJobConfirm_btn = QtWidgets.QDialogButtonBox(self.CreateJobWidget)
        self.CreateJobConfirm_btn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.CreateJobConfirm_btn.setObjectName("CreateJobConfirm_btn")
        self.verticalLayout_2.addWidget(self.CreateJobConfirm_btn)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.CreateJobWidget, "")
        self.ConfirmJobWidget = QtWidgets.QWidget()
        self.ConfirmJobWidget.setObjectName("ConfirmJobWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ConfirmJobWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.ConfirmJobWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.Deposit_CheckBox = QtWidgets.QCheckBox(self.ConfirmJobWidget)
        self.Deposit_CheckBox.setChecked(True)
        self.Deposit_CheckBox.setObjectName("Deposit_CheckBox")
        self.horizontalLayout_10.addWidget(self.Deposit_CheckBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.ConfirmJobWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.DepositDate_date = QtWidgets.QDateEdit(self.ConfirmJobWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DepositDate_date.sizePolicy().hasHeightForWidth())
        self.DepositDate_date.setSizePolicy(sizePolicy)
        self.DepositDate_date.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.DepositDate_date.setCalendarPopup(True)
        self.DepositDate_date.setDate(QtCore.QDate(2016, 1, 1))
        self.DepositDate_date.setObjectName("DepositDate_date")
        self.horizontalLayout_12.addWidget(self.DepositDate_date)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_18 = QtWidgets.QLabel(self.ConfirmJobWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_26.addWidget(self.label_18)
        self.StartDate_date = QtWidgets.QDateEdit(self.ConfirmJobWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartDate_date.sizePolicy().hasHeightForWidth())
        self.StartDate_date.setSizePolicy(sizePolicy)
        self.StartDate_date.setCalendarPopup(True)
        self.StartDate_date.setObjectName("StartDate_date")
        self.horizontalLayout_26.addWidget(self.StartDate_date)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.ConfirmJobConfirm_btn = QtWidgets.QDialogButtonBox(self.ConfirmJobWidget)
        self.ConfirmJobConfirm_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ConfirmJobConfirm_btn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ConfirmJobConfirm_btn.setCenterButtons(True)
        self.ConfirmJobConfirm_btn.setObjectName("ConfirmJobConfirm_btn")
        self.verticalLayout_7.addWidget(self.ConfirmJobConfirm_btn)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.JobIDprint_field = QtWidgets.QLabel(self.ConfirmJobWidget)
        self.JobIDprint_field.setEnabled(True)
        self.JobIDprint_field.setSizeIncrement(QtCore.QSize(30, 0))
        self.JobIDprint_field.setBaseSize(QtCore.QSize(30, 20))
        self.JobIDprint_field.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.JobIDprint_field.setObjectName("JobIDprint_field")
        self.horizontalLayout_11.addWidget(self.JobIDprint_field, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.ConfirmJobWidget, "")
        self.RevisionWidget = QtWidgets.QWidget()
        self.RevisionWidget.setEnabled(True)
        self.RevisionWidget.setObjectName("RevisionWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.RevisionWidget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_12 = QtWidgets.QLabel(self.RevisionWidget)
        self.label_12.setEnabled(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_20.addWidget(self.label_12)
        self.PlanCheckReturn_date = QtWidgets.QDateEdit(self.RevisionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlanCheckReturn_date.sizePolicy().hasHeightForWidth())
        self.PlanCheckReturn_date.setSizePolicy(sizePolicy)
        self.PlanCheckReturn_date.setCalendarPopup(True)
        self.PlanCheckReturn_date.setObjectName("PlanCheckReturn_date")
        self.horizontalLayout_20.addWidget(self.PlanCheckReturn_date)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_13 = QtWidgets.QLabel(self.RevisionWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_21.addWidget(self.label_13)
        self.EngRevisionDays_spin = QtWidgets.QSpinBox(self.RevisionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EngRevisionDays_spin.sizePolicy().hasHeightForWidth())
        self.EngRevisionDays_spin.setSizePolicy(sizePolicy)
        self.EngRevisionDays_spin.setObjectName("EngRevisionDays_spin")
        self.horizontalLayout_21.addWidget(self.EngRevisionDays_spin)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_14 = QtWidgets.QLabel(self.RevisionWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_22.addWidget(self.label_14)
        self.DraftRevisionDays_spin = QtWidgets.QSpinBox(self.RevisionWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DraftRevisionDays_spin.sizePolicy().hasHeightForWidth())
        self.DraftRevisionDays_spin.setSizePolicy(sizePolicy)
        self.DraftRevisionDays_spin.setObjectName("DraftRevisionDays_spin")
        self.horizontalLayout_22.addWidget(self.DraftRevisionDays_spin)
        self.verticalLayout_9.addLayout(self.horizontalLayout_22)
        self.RevisionConfirm_btn = QtWidgets.QDialogButtonBox(self.RevisionWidget)
        self.RevisionConfirm_btn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.RevisionConfirm_btn.setObjectName("RevisionConfirm_btn")
        self.verticalLayout_9.addWidget(self.RevisionConfirm_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.RevisionWidget, "")
        self.EditJobWidget = QtWidgets.QWidget()
        self.EditJobWidget.setObjectName("EditJobWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.EditJobWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Changes = QtWidgets.QTabWidget(self.EditJobWidget)
        self.Changes.setObjectName("Changes")
        self.SchedChange_tab = QtWidgets.QWidget()
        self.SchedChange_tab.setObjectName("SchedChange_tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.SchedChange_tab)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_10 = QtWidgets.QLabel(self.SchedChange_tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_17.addWidget(self.label_10)
        self.EngDead_btn = QtWidgets.QCheckBox(self.SchedChange_tab)
        self.EngDead_btn.setObjectName("EngDead_btn")
        self.horizontalLayout_17.addWidget(self.EngDead_btn)
        self.DftDead_btn = QtWidgets.QCheckBox(self.SchedChange_tab)
        self.DftDead_btn.setObjectName("DftDead_btn")
        self.horizontalLayout_17.addWidget(self.DftDead_btn)
        self.PlanCheck_btn = QtWidgets.QCheckBox(self.SchedChange_tab)
        self.PlanCheck_btn.setObjectName("PlanCheck_btn")
        self.horizontalLayout_17.addWidget(self.PlanCheck_btn)
        self.EngRevision_btn = QtWidgets.QCheckBox(self.SchedChange_tab)
        self.EngRevision_btn.setObjectName("EngRevision_btn")
        self.horizontalLayout_17.addWidget(self.EngRevision_btn)
        self.DftRevision_btn = QtWidgets.QCheckBox(self.SchedChange_tab)
        self.DftRevision_btn.setObjectName("DftRevision_btn")
        self.horizontalLayout_17.addWidget(self.DftRevision_btn)
        self.Final_btn = QtWidgets.QCheckBox(self.SchedChange_tab)
        self.Final_btn.setObjectName("Final_btn")
        self.horizontalLayout_17.addWidget(self.Final_btn)
        self.SchedAll_btn = QtWidgets.QCheckBox(self.SchedChange_tab)
        self.SchedAll_btn.setObjectName("SchedAll_btn")
        self.horizontalLayout_17.addWidget(self.SchedAll_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_11 = QtWidgets.QLabel(self.SchedChange_tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_18.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.PushDays_spin = QtWidgets.QSpinBox(self.SchedChange_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushDays_spin.sizePolicy().hasHeightForWidth())
        self.PushDays_spin.setSizePolicy(sizePolicy)
        self.PushDays_spin.setObjectName("PushDays_spin")
        self.horizontalLayout_18.addWidget(self.PushDays_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.SchedChange_tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.EngDeadline_date = QtWidgets.QDateEdit(self.SchedChange_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EngDeadline_date.sizePolicy().hasHeightForWidth())
        self.EngDeadline_date.setSizePolicy(sizePolicy)
        self.EngDeadline_date.setCalendarPopup(True)
        self.EngDeadline_date.setObjectName("EngDeadline_date")
        self.horizontalLayout_7.addWidget(self.EngDeadline_date)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.SchedChange_tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.DftDeadline_date = QtWidgets.QDateEdit(self.SchedChange_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DftDeadline_date.sizePolicy().hasHeightForWidth())
        self.DftDeadline_date.setSizePolicy(sizePolicy)
        self.DftDeadline_date.setCalendarPopup(True)
        self.DftDeadline_date.setObjectName("DftDeadline_date")
        self.horizontalLayout_6.addWidget(self.DftDeadline_date)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.SchedChange_tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.PlanCheck_date = QtWidgets.QDateEdit(self.SchedChange_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlanCheck_date.sizePolicy().hasHeightForWidth())
        self.PlanCheck_date.setSizePolicy(sizePolicy)
        self.PlanCheck_date.setCalendarPopup(True)
        self.PlanCheck_date.setObjectName("PlanCheck_date")
        self.horizontalLayout_8.addWidget(self.PlanCheck_date)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.SchedChange_tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.EngRevision_date = QtWidgets.QDateEdit(self.SchedChange_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EngRevision_date.sizePolicy().hasHeightForWidth())
        self.EngRevision_date.setSizePolicy(sizePolicy)
        self.EngRevision_date.setCalendarPopup(True)
        self.EngRevision_date.setObjectName("EngRevision_date")
        self.horizontalLayout_13.addWidget(self.EngRevision_date)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_7 = QtWidgets.QLabel(self.SchedChange_tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.label_7)
        self.DftRevision_date = QtWidgets.QDateEdit(self.SchedChange_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DftRevision_date.sizePolicy().hasHeightForWidth())
        self.DftRevision_date.setSizePolicy(sizePolicy)
        self.DftRevision_date.setCalendarPopup(True)
        self.DftRevision_date.setObjectName("DftRevision_date")
        self.horizontalLayout_14.addWidget(self.DftRevision_date)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.SchedChange_tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_15.addWidget(self.label_8)
        self.FinalDeadline_date = QtWidgets.QDateEdit(self.SchedChange_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FinalDeadline_date.sizePolicy().hasHeightForWidth())
        self.FinalDeadline_date.setSizePolicy(sizePolicy)
        self.FinalDeadline_date.setCalendarPopup(True)
        self.FinalDeadline_date.setObjectName("FinalDeadline_date")
        self.horizontalLayout_15.addWidget(self.FinalDeadline_date)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.ScheduleConfirm_btn = QtWidgets.QDialogButtonBox(self.SchedChange_tab)
        self.ScheduleConfirm_btn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ScheduleConfirm_btn.setObjectName("ScheduleConfirm_btn")
        self.verticalLayout.addWidget(self.ScheduleConfirm_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_11.addLayout(self.verticalLayout)
        self.Changes.addTab(self.SchedChange_tab, "")
        self.JobDetail_tab = QtWidgets.QWidget()
        self.JobDetail_tab.setObjectName("JobDetail_tab")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.JobDetail_tab)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.JobDetail_tab)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.DesignerEdit_txt = QtWidgets.QLineEdit(self.JobDetail_tab)
        self.DesignerEdit_txt.setObjectName("DesignerEdit_txt")
        self.horizontalLayout_16.addWidget(self.DesignerEdit_txt)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_16 = QtWidgets.QLabel(self.JobDetail_tab)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_23.addWidget(self.label_16)
        self.JobNameEdit_txt = QtWidgets.QLineEdit(self.JobDetail_tab)
        self.JobNameEdit_txt.setObjectName("JobNameEdit_txt")
        self.horizontalLayout_23.addWidget(self.JobNameEdit_txt)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_17 = QtWidgets.QLabel(self.JobDetail_tab)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_25.addWidget(self.label_17)
        self.ContractorEdit_txt = QtWidgets.QLineEdit(self.JobDetail_tab)
        self.ContractorEdit_txt.setObjectName("ContractorEdit_txt")
        self.horizontalLayout_25.addWidget(self.ContractorEdit_txt)
        self.verticalLayout_12.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_21 = QtWidgets.QLabel(self.JobDetail_tab)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_29.addWidget(self.label_21)
        self.APNEdit_txt = QtWidgets.QLineEdit(self.JobDetail_tab)
        self.APNEdit_txt.setObjectName("APNEdit_txt")
        self.horizontalLayout_29.addWidget(self.APNEdit_txt)
        self.verticalLayout_12.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_22 = QtWidgets.QLabel(self.JobDetail_tab)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_30.addWidget(self.label_22)
        self.AddressEdit_txt = QtWidgets.QLineEdit(self.JobDetail_tab)
        self.AddressEdit_txt.setObjectName("AddressEdit_txt")
        self.horizontalLayout_30.addWidget(self.AddressEdit_txt)
        self.verticalLayout_12.addLayout(self.horizontalLayout_30)
        self.JobEditConfirm_btn = QtWidgets.QDialogButtonBox(self.JobDetail_tab)
        self.JobEditConfirm_btn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.JobEditConfirm_btn.setObjectName("JobEditConfirm_btn")
        self.verticalLayout_12.addWidget(self.JobEditConfirm_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.Changes.addTab(self.JobDetail_tab, "")
        self.verticalLayout_4.addWidget(self.Changes)
        self.tabWidget.addTab(self.EditJobWidget, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.DayViewTitle_txt = QtWidgets.QLabel(self.centralwidget)
        self.DayViewTitle_txt.setObjectName("DayViewTitle_txt")
        self.verticalLayout_15.addWidget(self.DayViewTitle_txt)
        self.DayView_lst = QtWidgets.QListWidget(self.centralwidget)
        self.DayView_lst.setObjectName("DayView_lst")
        self.verticalLayout_15.addWidget(self.DayView_lst)
        self.horizontalLayout_24.addLayout(self.verticalLayout_15)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem3)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setAutoFillBackground(True)
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.LongDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_24.addWidget(self.calendarWidget)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        JobSchedulerUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JobSchedulerUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 22))
        self.menubar.setObjectName("menubar")
        JobSchedulerUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JobSchedulerUI)
        self.statusbar.setObjectName("statusbar")
        JobSchedulerUI.setStatusBar(self.statusbar)

        self.retranslateUi(JobSchedulerUI)
        self.tabWidget.setCurrentIndex(0)
        self.Changes.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(JobSchedulerUI)

    def retranslateUi(self, JobSchedulerUI):
        _translate = QtCore.QCoreApplication.translate
        JobSchedulerUI.setWindowTitle(_translate("JobSchedulerUI", "Job Scheduler"))
        self.JobInProgressCounter.setText(_translate("JobSchedulerUI", "Jobs In Progress : 000"))
        self.JobInPlanCheckCounter.setText(_translate("JobSchedulerUI", "Jobs In Plan Check : 000"))
        self.label.setText(_translate("JobSchedulerUI", "Designer :"))
        self.jobName.setText(_translate("JobSchedulerUI", "Job Name :"))
        self.contractorName.setText(_translate("JobSchedulerUI", "Contractor :"))
        self.eng_days.setText(_translate("JobSchedulerUI", "Engineering Days :"))
        self.draft_days.setText(_translate("JobSchedulerUI", "Drafting Days :"))
        self.start_date.setText(_translate("JobSchedulerUI", "Estimated Starting Date :"))
        self.EstStartDay_date.setDisplayFormat(_translate("JobSchedulerUI", "M/d/yyyy"))
        self.label_19.setText(_translate("JobSchedulerUI", "APN :"))
        self.label_20.setText(_translate("JobSchedulerUI", "Address :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CreateJobWidget), _translate("JobSchedulerUI", "Create New Job"))
        self.label_6.setText(_translate("JobSchedulerUI", "Deposit Recieved Today?"))
        self.Deposit_CheckBox.setText(_translate("JobSchedulerUI", "Yes"))
        self.label_9.setText(_translate("JobSchedulerUI", "Date Recieved :"))
        self.DepositDate_date.setDisplayFormat(_translate("JobSchedulerUI", "M/d/yyyy"))
        self.label_18.setText(_translate("JobSchedulerUI", "Starting Date :"))
        self.StartDate_date.setDisplayFormat(_translate("JobSchedulerUI", "M/d/yyyy"))
        self.JobIDprint_field.setText(_translate("JobSchedulerUI", "Job ID : 00000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ConfirmJobWidget), _translate("JobSchedulerUI", "Confirm Job"))
        self.RevisionWidget.setAccessibleName(_translate("JobSchedulerUI", "Revision"))
        self.label_12.setText(_translate("JobSchedulerUI", "Plan Check Return Date :"))
        self.PlanCheckReturn_date.setDisplayFormat(_translate("JobSchedulerUI", "M/d/yyyy"))
        self.label_13.setText(_translate("JobSchedulerUI", "Engineering Revision Days :"))
        self.label_14.setText(_translate("JobSchedulerUI", "Drafting Revision Days :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RevisionWidget), _translate("JobSchedulerUI", "Revisions"))
        self.label_10.setText(_translate("JobSchedulerUI", "Push Dates :"))
        self.EngDead_btn.setText(_translate("JobSchedulerUI", "Eng D"))
        self.DftDead_btn.setText(_translate("JobSchedulerUI", "Dft D"))
        self.PlanCheck_btn.setText(_translate("JobSchedulerUI", "PCS"))
        self.EngRevision_btn.setText(_translate("JobSchedulerUI", "Eng R"))
        self.DftRevision_btn.setText(_translate("JobSchedulerUI", "Dft R"))
        self.Final_btn.setText(_translate("JobSchedulerUI", "Final"))
        self.SchedAll_btn.setText(_translate("JobSchedulerUI", "All"))
        self.label_11.setText(_translate("JobSchedulerUI", "How Many Days?"))
        self.label_2.setText(_translate("JobSchedulerUI", "Engineering Deadline :"))
        self.EngDeadline_date.setDisplayFormat(_translate("JobSchedulerUI", "M/d/yyyy"))
        self.label_3.setText(_translate("JobSchedulerUI", "Drafting Deadline :"))
        self.DftDeadline_date.setDisplayFormat(_translate("JobSchedulerUI", "M/d/yyyy"))
        self.label_4.setText(_translate("JobSchedulerUI", "Plan Check Submital :"))
        self.PlanCheck_date.setDisplayFormat(_translate("JobSchedulerUI", "M/d/yyyy"))
        self.label_5.setText(_translate("JobSchedulerUI", "Engineering Revision :"))
        self.EngRevision_date.setDisplayFormat(_translate("JobSchedulerUI", "M/d/yyyy"))
        self.label_7.setText(_translate("JobSchedulerUI", "Drafting Revision :"))
        self.DftRevision_date.setDisplayFormat(_translate("JobSchedulerUI", "M/d/yyyy"))
        self.label_8.setText(_translate("JobSchedulerUI", "Final Deadline :"))
        self.FinalDeadline_date.setDisplayFormat(_translate("JobSchedulerUI", "M/d/yyyy"))
        self.Changes.setTabText(self.Changes.indexOf(self.SchedChange_tab), _translate("JobSchedulerUI", "Schedule Change"))
        self.label_15.setText(_translate("JobSchedulerUI", "Designer :"))
        self.label_16.setText(_translate("JobSchedulerUI", "Job Name :"))
        self.label_17.setText(_translate("JobSchedulerUI", "Contractor :"))
        self.label_21.setText(_translate("JobSchedulerUI", "APN :"))
        self.label_22.setText(_translate("JobSchedulerUI", "Address :"))
        self.Changes.setTabText(self.Changes.indexOf(self.JobDetail_tab), _translate("JobSchedulerUI", "Job Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EditJobWidget), _translate("JobSchedulerUI", "Edit Job"))
        self.DayViewTitle_txt.setText(_translate("JobSchedulerUI", "TextLabel"))

